flash; imgbackup: align

diff --git a/recipes-images/base-files/files/flash b/recipes-images/base-files/files/flash
--- a/recipes-images/base-files/files/flash
+++ b/recipes-images/base-files/files/flash
@@ -2,16 +2,16 @@
 
 machine="hd60"
 url="https://tuxbox-images.de/images/$machine"
-image="neutrino-image_ofgwrite.zip"
+image="OpenEmbedded-warrior-hd60_mmc.zip"
 imagesource="$url/$image"
 hdd_mount="/media/usb"
-mountpoint -q /media/hdd && hdd_mount="/media/hdd"
+mountpoint -q /media/sdcard && hdd_mount="/media/sdcard"
 destination="/mnt/userdata"
 imagebase="$hdd_mount/service/image"
 imageversion_online="$url/imageversion"
 picture_source="/usr/share/tuxbox/neutrino/icons"
 rootfs="rootfs.tar.bz2"
-kernel_bin="kernel.bin"
+kernel_bin="uImage"
 rootbase="linuxrootfs"
 kernelbase="linuxkernel"
 devbase="/dev/disk/by-partlabel"
@@ -37,7 +37,7 @@ exit_done() {
 		exit 0;
 	else
 		sleep 3
-		clear
+#		clear
 		pidof neutrino >> /dev/null || systemctl start neutrino
 		exit 0;
 	fi
@@ -53,7 +53,7 @@ if [[ $1 =~ ^[0-9]+$ ]]; then
 	if  [ $1 -lt 1 ] || [ $1 -gt 4 ]; then
 		printf '\n\033[31m%s\n' "Choose a valid partition [1-4]" ; exit 1;
 	elif [ $1 = 1 ]; then
-		part=1; append=""
+		part=1; append=$part
 	elif [ $1 = 2 ]; then
 		part=2; append=$part
 	elif [ $1 = 3 ]; then
@@ -93,22 +93,26 @@ if [[ ! $1 = "force" ]] && [[ ! $2 = "force" ]]; then
 				restore)
 					imagedir="$imagebase/backup/partition_$part/$machine"
 					restore_image="1"
+					imagefile="$imagebase/backup/partition_$part/$image"
 					;;
 				1|2|3|4)
 					imagedir="$2"
 					;;
 				/*)
-					imagedir="$2"
+					imagedir="$2/$machine"
+					imagefile="$2/$image"
 					;;
 				"")
-					imagedir="$1"
+					imagedir="$1/$machine"
 					;;
 			esac
 		done
 		imageversion="$imagedir/imageversion"
 		[[ -f $imageversion ]] && [[ -d $imagebase ]] && cp -rf $imageversion $imageversion_local
-		[ ! -f $imagedir/$rootfs ] && printf '\n%s\n' "$imagedir/$rootfs not found" && exit_done
-		[ ! -f $imagedir/$kernel_bin ] && printf '\n%s\n' "$imagedir/$kernel_bin not found" && exit_done
+		[ -d $imagedir ] || mkdir -p $imagedir
+                unzip -xo $imagefile -d $imagedir || exit_done;
+		[ ! -f $imagedir/$machine/$rootfs ] && printf '\n%s\n' "$imagedir/$rootfs not found" && exit_done
+		[ ! -f $imagedir/$machine/$kernel_bin ] && printf '\n%s\n' "$imagedir/$kernel_bin not found" && exit_done
 		space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
 		[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on your device" && exit_done
 		write_image
@@ -138,7 +142,7 @@ if [[ -z $1 ]] || [[ $* = "force" ]] || [[ ! $* = "restore" ]] || [[ $1 =~ ^[0-9
 			fi
 			echo "Downloading $image" > $dev_display
 			printf '\n\033[1m%s\n\033[0m' "Downloading $imagesource"
-			unpack="unzip -x $imagefile -d $imagebase"
+			unpack="unzip -xo $imagefile -d $imagebase"
 			curl $imagesource -o $imagefile || exit_done
 			[ -d $imagedir ] && rm -r $imagedir
 			echo "Decompressing $image" > $dev_display
